main: me.MathiasMC.PvPTeams.PvPTeams
version: ${project.version}
name: ${project.name}
author: MathiasMC
description: ${project.description}
website: spigotmc.org/resources/pvpteams.80970
api-version: 1.13
commands:
  pvpteams:
    description: PvPTeams main command
    aliases: [team]
  pvpmenu:
    description: PvPMenu gui